### ISSUE TITLE
Knapster is saving a log file to the desktop [BUG]

### ISSUE THREAD

**Issue by Ricoware** [ApacheTech-VintageStory-Mods/Knapster#11]
A file called "harmony.log.txt" is being saved to the desktop, on both the server machine, and each client's machine.  This file should be created in the appropriate VS folder, not the desktop, if it needs to be created at all.

[harmony.log.txt](https://github.com/ApacheTech-VintageStory-Mods/Knapster/files/14547280/harmony.log.txt)

**Comment by ApacheTech** [comment]
This has already been fixed, if you re-download the mod. :)

**Comment by Ricoware** [comment]
As you can see in the harmony.log.txt file I attached yesterday, I'm running version 2.9.2 of Knapster, which is the latest version available, and I'm still getting the log file.

**Comment by ApacheTech** [comment]
Delete the zip file you have, and re-download the same version.
