### ISSUE TITLE
[BUG] mod seems disabled after using .charsel

### ISSUE THREAD

**Issue by Fatboye206** [ApacheTech-VintageStory-Mods/Knapster#12]
The mod worked just fine until I remade my character using .charsel, after which point the knapping feature disabled itself and I wasn't able to use commands to turn it back on. If the knapster command is supposed to be listed when using /help, then it also no longer appears on the list.

To Reproduce:
Steps to reproduce the behaviour:
download knapster
load into world
use /player yourname allowcharselonce
use .charsel
use /knapster k mode enabled

Expected Behaviour:
Clicking and holding on knapping sites automatically breaks voxels, commands change mod behavior

Additional Context
I use a heavy mod load on a gaming laptop, and it's possible that a crash could have messed with some data. Looking through the logs myself I don't see any obvious error messages mentioning knapster, but obviously you have more experience with your mod.

[client-crash.txt](https://github.com/user-attachments/files/16117878/client-crash.txt)
[client-debug.txt](https://github.com/user-attachments/files/16117879/client-debug.txt)
[client-main.txt](https://github.com/user-attachments/files/16117880/client-main.txt)
[server-audit.txt](https://github.com/user-attachments/files/16117881/server-audit.txt)
[server-debug.txt](https://github.com/user-attachments/files/16117884/server-debug.txt)
[server-event.txt](https://github.com/user-attachments/files/16117885/server-event.txt)
[server-main.txt](https://github.com/user-attachments/files/16117886/server-main.txt)
[server-storyevent.txt](https://github.com/user-attachments/files/16117887/server-storyevent.txt)
[server-worldgen.txt](https://github.com/user-attachments/files/16117888/server-worldgen.txt)
[xlevelingdescription.txt](https://github.com/user-attachments/files/16117889/xlevelingdescription.txt)

**Comment by ApacheTech** [comment]
I'm hoping this this issue will now be resolved in v2.9.5.

**Comment by Fatboye206** [comment]
Works great now, thanks!
