### ISSUE TITLE
[BUG] Unable to add to whitelist

### ISSUE THREAD

**Issue by c1charge** [ApacheTech-VintageStory-Mods/Knapster#13]
Hello, we are unable to add anyone to a whitelist on our server using this mod. It did work one time, but after that we only get this error when attempting to add another player:

[Error] Exception: Object reference not set to an instance of an object. at ApacheTech.VintageMods.Knapster.ChatCommands.Parsers.FuzzyPlayerParser.<>cDisplayClass12_0.<FuzzyPlayerSearch>b0(ServerPlayer client) at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source) at ApacheTech.VintageMods.Knapster.ChatCommands.Parsers.FuzzyPlayerParser.TryProcess(TextCommandCallingArgs args, Action1 onReady) at Vintagestory.Common.ChatCommandImpl.Execute(TextCommandCallingArgs callargs, Action1 onCommandComplete) at Vintagestory.Common.ChatCommandImpl.CallHandler(TextCommandCallingArgs callargs, Action1 onCommandComplete, Dictionary2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 259 at Vintagestory.Common.ChatCommandImpl.CallHandler(TextCommandCallingArgs callargs, Action1 onCommandComplete, Dictionary2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 259 at Vintagestory.Common.ChatCommandApi.Execute(String commandName, TextCommandCallingArgs args, Action1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 88 at Vintagestory.Common.ChatCommandApi.Execute(String commandName, IServerPlayer player, Int32 groupId, String args, Action1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 181

Then, sometimes if you just do the /knapster (mode) whitelist command it seems like it rememebers the last time you tried to whitelist someone and throws this warning:
[Notification] Handling Command (c1charge) /knapster clayforming whitelist
[Warning] Translation string format exception thrown for: "The search for '{c1charge}' yielded no results. Please try again." Args were:
 
We are on 1.19.8, and running this list of mods:
Rustbound Magic, Feverstone Wilds, Crossbows, QP's Chisel Tools, Vinconmy, Primitive Survival, Alchemy, You've Got Mail, Better Ruins, Better Traders, Pet AI, DiscordBot, A Culinary Artilery, Expanded Foods, Vanity, Ancient Armory, Improved Lit Torch Recipe, VanillaPlus, WorldGen, Hanging Baskets, VS Quest, Whole Lotta Tree Seeds, SilentSave
 
Any help would be appreciated, as we have players who would really benefit from being able to use this mods features. Thanks!

**Comment by ApacheTech** [comment]
I'm hoping this this issue will now be resolved in v2.9.5.
