### ISSUE TITLE
Clay Autocomplete Eats Voxels

### ISSUE THREAD

**Issue by xy172** [ApacheTech-VintageStory-Mods/Knapster#21]
# 🐛 Bug Report

When using autocomplete and picking back up clay voxels, they are instead consumed.

## 🤔 Expected Behaviour

When manually picking back up voxels they are added back to your count. Autocomplete should do the same.

**Comment by ApacheTech** [comment]
How are you able to pick up voxels with AutoComplete on? You shouldn't be able to remove clay at all when in that mode.

**Comment by xy172** [comment]
When in that mode you can not but any left over, either incorrectly placed by the user or from the starter square subtract from the vowel count rather than adding to it. For example when making 4 bowls you lose all the clay it places for you in-between the bowls when first starting the craft.

**Comment by xy172** [comment]
When in that mode you can not but any left over, either incorrectly placed by the user or from the starter square subtract from the vowel count rather than adding to it. For example when making 4 bowls you lose all the clay it places for you in-between the bowls when first starting the craft.

**Comment by xy172** [comment]
Oops

**Comment by ApacheTech** [comment]
I understand now. I'll have a look today.

**Comment by ApacheTech** [comment]
Fixed, and will be released in v2.11.1.
