### ISSUE TITLE
[BUG] 1.19.3 not supported

### ISSUE THREAD

**Issue by ChristianANoeddeboe** [ApacheTech-VintageStory-Mods/Knapster#6]
**Describe the Bug:**
Game crashes on startup with the mod installed on a 1.19.3 client. Installing to a server seems to just not enable the mod at all.

**Additional Context**
Attached my client crash log
[client-crash.txt](https://github.com/ApacheTech-VintageStory-Mods/Knapster/files/14082953/client-crash.txt)

**Comment by ApacheTech** [comment]
Thank you, this issue has been tagged, and routed for triage.
