### ISSUE TITLE
[BUG] Knapping flint requires a different stone held in hand

### ISSUE THREAD

**Issue by devpikachu** [ApacheTech-VintageStory-Mods/Knapster#8]
**Describe the Bug:**
If knapping flint, the mod doesn't function unless a different stone is held in hand.

**To Reproduce:**
Steps to reproduce the behaviour:
1. Get 2 pieces of flint
2. Knap any pattern

**Expected Behaviour:**
The knapping works like with the other stones

**Additional Context**
N/A

**Comment by ApacheTech** [comment]
I cannot re-produce this issue within v2.7.0, on game v1.19.3.

It's possible that you may have some left over assets from previous versions. Ensure you do not have any previous versions within your mods folder, you mod cache folder, and your mod data folder. That would be my first point of call.

**Comment by PetarPeychev** [comment]
I have the same issue with v2.8.1 on v1.19.3, running on Linux. I just installed the mod with no previous installation and tried it on an existing save. Can knap flint tools while holding chalk, but not flint.

**Comment by ApacheTech** [comment]
I can't do anything without log files.

I also have no way of testing anything on Linux.

I will need `client-debug.txt`, `client-main.txt`, `server-debug.txt`, and `server-main.txt`.
